### ISSUE TITLE
Initial B2 errors

### ISSUE THREAD

**Issue by andypullen** [weareferal/craft-remote-backup#20]
After setting up the plugin and running it both through the queue and independently, it's unable to fetch the database and volumes.

When running `$ ./craft remote-backup/database/create` this is the error that occurs:
```
Cannot load Zend OPcache - it was already loaded
Error: The shell command "mysqldump --defaults-extra-file="/var/www/html/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --single-transaction --no-data --result-file="/var/www/html/storage/remote-backup/central-cms_production_200729_133953_wy3ejgzxua_v3.4.30.sql" craft && mysqldump --defaults-extra-file="/var/www/html/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-create-info --ignore-table=craft.craft_assetindexdata --ignore-table=craft.craft_assettransformindex --ignore-table=craft.craft_sessions --ignore-table=craft.craft_templatecaches --ignore-table=craft.craft_templatecachequeries --ignore-table=craft.craft_templatecacheelements --ignore-table=craft.craft_cache --ignore-table=craft.craft_templatecachecriteria craft >> "/var/www/html/storage/remote-backup/central-cms_production_200729_133953_wy3ejgzxua_v3.4.30.sql"" failed with exit code 1: mysqldump: Can't create/write to file '/var/www/html/storage/remote-backup/central-cms_production_200729_133953_wy3ejgzxua_v3.4.30.sql' (Errcode: 13)
```

When running `$ ./craft remote-backup/database/list` this error occurs:
```
Cannot load Zend OPcache - it was already loaded
Exception 'Error' with message 'Class 'Aws\S3\S3Client' not found'

in /var/www/html/vendor/weareferal/remote-core/src/services/providers/AWSProvider.php:180

Stack trace:
#0 /var/www/html/vendor/weareferal/remote-core/src/services/providers/AWSProvider.php(52): weareferal\remotecore\services\providers\AWSProvider->getClient()
#1 /var/www/html/vendor/weareferal/remote-core/src/services/ProviderService.php(84): weareferal\remotecore\services\providers\AWSProvider->list('.sql')
#2 /var/www/html/vendor/weareferal/remote-backup/src/console/controllers/DatabaseController.php(40): weareferal\remotecore\services\ProviderService->listDatabases()
#3 [internal function]: weareferal\remotebackup\console\controllers\DatabaseController->actionList()
#4 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#6 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('list', Array)
#7 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('list', Array)
#8 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('remote-backup/d...', Array)
#9 /var/www/html/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('remote-backup/d...', Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('remote-backup/d...', Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#12 /var/www/html/craft(22): yii\base\Application->run()
#13 {main}
```
I'm pretty certain my B2 credentials are correct, and are being passed in through env variables. I setup the application key twice, and uninstalled and reinstalled the plugin as well with the same effect. I'm new to B2 so it could be settings on that end although it looks like the create command is outputting a permissions error and the list command seems to be attempting to call a class that doesn't exist. Any ideas?

**Comment by timmyomahony** [comment]
Hey @andypullen have you installed the separate AWS client library? Outlined here:

https://github.com/weareferal/craft-remote-backup/wiki/Amazon-S3

```
composer require aws/aws-sdk-php:^3
```

It looks like there's possibly two different issues going on here. Regarding the first, it looks like the path you are saving to `/var/www/html/storage` might not exists or doesn't have the correct permissions?

**Comment by andypullen** [comment]
Hey @timmyomahony thank you – I somehow missed the AWS client library, and that did indeed solve the issue with the list command. And you were also correct about the other issue being a permissions issue. Fixing permissions on the storage directory did the trick.

**Comment by timmyomahony** [comment]
Glad you got it working
